branches:
  - name: master
  - name: next
    prerelease: true

tagFormat: release/${version}

preset: eslint

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
