name: Build Runner

on:
  push:
    branches:
      - master
    paths:
      - ./runners

jobs:
  build:
    name: Build
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        runtime:
          - node

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - env:
          IMAGE: ${{ steps.login-ecr.outputs.registry }}/gha-runner:${{ matrix.runtime }}
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
