name: Build Runner

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - runner/**
      - .github/workflows/build-runner.yaml

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        env:
          # this seems to be the only endpoint available for ECR?
          AWS_REGION: us-east-1

      - uses: actions/checkout@v3

      - name: Build image
        env:
          IMAGE: public.ecr.aws/t4g8t3e5/gha-runner:latest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        run: |
          docker run --rm \
            -v $(pwd)/runner:/workspace \
            -e AWS_ACCESS_KEY \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_SDK_LOAD_CONFIG=true \
            gcr.io/kaniko-project/executor:debug \
              --cache \
              --destination=${{ env.IMAGE }} \
              --reproducible

      - uses: hans-m-song/actions/prune-ecr-repository@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          repository-name: huisheng
