name: Build Runner

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - ./runners/**/*

jobs:
  build:
    name: Build
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        runtime:
          - node
          - go

    steps:
      - uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        env:
          # this seems to be the only endpoint available for ECR?
          AWS_REGION: us-east-1

      - uses: actions/checkout@v3

      - run: |
          docker pull $IMAGE
          docker build --cache-from $IMAGE -t $IMAGE ./runners/${{ matrix.runtime }}
          docker push $IMAGE
        env:
          IMAGE: public.ecr.aws/t4g8t3e5/gha-runner-${{ matrix.runtime }}:latest
