name: Release

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  release:
    name: Release
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Release dry run
        run: npx semantic-release -d
